# Generated by Django 5.1.6 on 2025-03-03 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='route',
            options={'ordering': ['departure_time'], 'verbose_name': 'Маршрут', 'verbose_name_plural': 'Маршруты'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['route', 'seat_number'], 'verbose_name': 'Билет', 'verbose_name_plural': 'Билеты'},
        ),
        migrations.AlterField(
            model_name='route',
            name='arrival_time',
            field=models.DateTimeField(verbose_name='Время прибытия'),
        ),
        migrations.AlterField(
            model_name='route',
            name='available_seats',
            field=models.IntegerField(verbose_name='Свободных мест'),
        ),
        migrations.AlterField(
            model_name='route',
            name='departure_time',
            field=models.DateTimeField(verbose_name='Время отправления'),
        ),
        migrations.AlterField(
            model_name='route',
            name='from_city',
            field=models.CharField(max_length=100, verbose_name='Город отправления'),
        ),
        migrations.AlterField(
            model_name='route',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='route',
            name='to_city',
            field=models.CharField(max_length=100, verbose_name='Город прибытия'),
        ),
        migrations.AlterField(
            model_name='route',
            name='total_seats',
            field=models.IntegerField(verbose_name='Всего мест'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='is_purchased',
            field=models.BooleanField(default=False, verbose_name='Куплен'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='purchase_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата покупки'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='admin_panel.route', verbose_name='Маршрут'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='seat_number',
            field=models.IntegerField(verbose_name='Номер места'),
        ),
    ]
